### ISSUE TITLE
"Trocar ul por dl"

### ISSUE THREAD

**Issue by AugustusTest** [NezzoNarcizo/Estudos#21]
"A lista de cursos pode ser melhor representada pela tag HTML "< dl >"".

**Comment by NezzoNarcizo** [comment]
> "A lista de cursos pode ser melhor representada pela tag HTML "< dl >"".

Fechado pelo PR #22

**Comment by NezzoNarcizo** [comment]
> "A lista de cursos pode ser melhor representada pela tag HTML "< dl >"".

**Comment by NezzoNarcizo** [comment]
Fechado pelo PR #22
